### Health
GET http://localhost:5000/

### Contacts
GET http://localhost:5000/api/contacts

POST http://localhost:5000/api/contacts
Content-Type: application/json

{
  "firstname": "Ramika",
  "lastname": "Dayananda",
  "email": "ramika@example.com"
}

### Users Auth
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@example.com",
  "password": "Passw0rd!"
}

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Passw0rd!"
}

GET http://localhost:5000/api/auth/me
Authorization: Bearer {{token}}
